# -*- coding: utf-8 -*-
"""Coleta_de_Dados.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1slf7HUB6Wo69FBYHTeOHSXmN04Madobn

##Importando Dados
"""

# Importando os Dados

import sqlite3
import pandas as pd
conn = sqlite3.connect( "database.db" )

# Consulta dos Dados no BD
consulta_atividade = """

  SELECT
    fa.loyalty_number,
    fa.year,
    fa.month,
    fa.flights_booked,
    fa.total_flights,
    fa.distance,
    fa.points_accumulated
  FROM
    flight_activity fa

"""
df_atividade = pd.read_sql_query( consulta_atividade, conn )

df_atividade.head()

# 1. Selecione as colunas: loyalty_number, country, city, gender, loyalty_card e salary da tabela "flight_loyalty_history"

consulta_atividade = """

  SELECT
    flh.loyalty_number,
    flh.country,
    flh.city,
    flh.gender,
    flh.loyalty_card,
    flh.salary
  FROM
    flight_loyalty_history flh

"""

df_atividade = pd.read_sql_query( consulta_atividade, conn )

df_atividade.head()

# 2. Selecione as mesmas colunas, porém, recupere somente as linhas cuja coluna gender é igual a Female da tabela flighy_loyalty_history

consulta_atividade = """

  SELECT
    flh.loyalty_number,
    flh.country,
    flh.city,
    flh.gender,
    flh.loyalty_card,
    flh.salary
  FROM
    flight_loyalty_history flh
  WHERE
    flh.gender = 'Female'

  """

df_atividade = pd.read_sql_query( consulta_atividade, conn )

df_atividade.head()

# 3. Selecione as colunas: loyalty_number, month, year, distance, flights_booked e total_flights da tabela flight_activity
# e recupere somente as linhas cuja coluna flights_booked é maior que 10 e menor que 12.

consulta_atividade = """

  SELECT
    fa.loyalty_number,
    fa.month,
    fa.year,
    fa.distance,
    fa.flights_booked,
    fa.total_flights
  FROM
    flight_activity fa
  WHERE
    fa.flights_booked > 10
  AND
    fa.flights_booked < 12

"""
df_atividade = pd.read_sql_query( consulta_atividade, conn )

df_atividade.head()

# Fecha a conexão com o banco de dados
#conn.close()